FROM mcr.microsoft.com/dotnet/aspnet:10.0@sha256:2d584d8147faddb0d678c5748d47953e5b8e18621ed4fb7049a91381d9d7746f AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0@sha256:35d40304542c8689331f8cab17c65926cdf48fe711e289321d71924b230a7d29 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Signal.Bot.Example/Signal.Bot.Example.csproj", "Signal.Bot.Example/"]
COPY ["Signal.Bot/Signal.Bot.csproj", "Signal.Bot/"]
RUN dotnet restore "Signal.Bot.Example/Signal.Bot.Example.csproj"
COPY . .
WORKDIR "/src/Signal.Bot.Example"
RUN dotnet build "./Signal.Bot.Example.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Signal.Bot.Example.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Signal.Bot.Example.dll"]
