FROM mcr.microsoft.com/dotnet/aspnet:10.0@sha256:6a94333d37514e385650a3c81a55e5350b67253dbe136e9cf17e499c35606a8c AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0@sha256:2fa828c68761b1b8c23d7662dc134421b9d3b59fe1425fdbc80804e390cdb24d AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Signal.Bot.Example/Signal.Bot.Example.csproj", "Signal.Bot.Example/"]
COPY ["Signal.Bot/Signal.Bot.csproj", "Signal.Bot/"]
RUN dotnet restore "Signal.Bot.Example/Signal.Bot.Example.csproj"
COPY . .
WORKDIR "/src/Signal.Bot.Example"
RUN dotnet build "./Signal.Bot.Example.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Signal.Bot.Example.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Signal.Bot.Example.dll"]
