using Signal.Bot.Requests;
using Signal.Bot.Types;

namespace Signal.Bot.Serialization;

[JsonSourceGenerationOptions(
    Converters = [typeof(TimestampConverter)],
    UseStringEnumConverter = true,
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
    WriteIndented = false,
    GenerationMode = JsonSourceGenerationMode.Default)]
[JsonSerializable(typeof(About))]
[JsonSerializable(typeof(Acknowledged))]
[JsonSerializable(typeof(Attachment))]
[JsonSerializable(typeof(Configuration))]
[JsonSerializable(typeof(Contact))]
[JsonSerializable(typeof(DataMessage))]
[JsonSerializable(typeof(Device))]
[JsonSerializable(typeof(Envelope))]
[JsonSerializable(typeof(Types.Error))]
[JsonSerializable(typeof(Group))]
[JsonSerializable(typeof(GroupV2Info))]
[JsonSerializable(typeof(Identity))]
[JsonSerializable(typeof(LoggingConfiguration))]
[JsonSerializable(typeof(Mention))]
[JsonSerializable(typeof(Nickname))]
[JsonSerializable(typeof(PreviewData))]
[JsonSerializable(typeof(Profile))]
[JsonSerializable(typeof(ProfileCapabilities))]
[JsonSerializable(typeof(QuoteData))]
[JsonSerializable(typeof(RawDeviceLink))]
[JsonSerializable(typeof(ReactionData))]
[JsonSerializable(typeof(ReadMessage))]
[JsonSerializable(typeof(ReceiptMessage))]
[JsonSerializable(typeof(ReceivedMessage))]
[JsonSerializable(typeof(Search))]
[JsonSerializable(typeof(SetUsername))]
[JsonSerializable(typeof(StickerPack))]
[JsonSerializable(typeof(SyncMessage))]
[JsonSerializable(typeof(TypingMessage))]
[JsonSerializable(typeof(AddDeviceRequest))]
[JsonSerializable(typeof(AddGroupAdminRequest))]
[JsonSerializable(typeof(AddGroupMemberRequest))]
[JsonSerializable(typeof(AddReactionRequest))]
[JsonSerializable(typeof(AddStickerPackRequest))]
[JsonSerializable(typeof(AddTypingIndicatorRequest))]
[JsonSerializable(typeof(BlockGroupRequest))]
[JsonSerializable(typeof(CreateGroupRequest))]
[JsonSerializable(typeof(GetAboutRequest))]
[JsonSerializable(typeof(GetAccountsRequest))]
[JsonSerializable(typeof(GetAttachmentRequest))]
[JsonSerializable(typeof(GetAttachmentsRequest))]
[JsonSerializable(typeof(GetConfigurationRequest))]
[JsonSerializable(typeof(GetContactRequest))]
[JsonSerializable(typeof(GetContactsRequest))]
[JsonSerializable(typeof(GetDevicesRequest))]
[JsonSerializable(typeof(GetGroupRequest))]
[JsonSerializable(typeof(GetGroupsRequest))]
[JsonSerializable(typeof(GetIdentitiesRequest))]
[JsonSerializable(typeof(GetQrCodeLinkRequest))]
[JsonSerializable(typeof(GetRawDeviceLinkRequest))]
[JsonSerializable(typeof(GetReceivedMessagesRequest))]
[JsonSerializable(typeof(GetStickerPacksRequest))]
[JsonSerializable(typeof(JoinGroupRequest))]
[JsonSerializable(typeof(QuitGroupRequest))]
[JsonSerializable(typeof(RateLimitChallengeRequest))]
[JsonSerializable(typeof(RegisterNumberRequest))]
[JsonSerializable(typeof(RemoteDeleteRequest))]
[JsonSerializable(typeof(RemoveAttachmentRequest))]
[JsonSerializable(typeof(RemoveGroupAdminRequest))]
[JsonSerializable(typeof(RemoveGroupMemberRequest))]
[JsonSerializable(typeof(RemoveGroupRequest))]
[JsonSerializable(typeof(RemovePinRequest))]
[JsonSerializable(typeof(RemoveReactionRequest))]
[JsonSerializable(typeof(RemoveTypingIndicatorRequest))]
[JsonSerializable(typeof(RemoveUsernameRequest))]
[JsonSerializable(typeof(SearchNumbersRequest))]
[JsonSerializable(typeof(SendMessageRequest))]
[JsonSerializable(typeof(SendReceiptsRequest))]
[JsonSerializable(typeof(SetConfigurationRequest))]
[JsonSerializable(typeof(SetPinRequest))]
[JsonSerializable(typeof(SetUsernameRequest))]
[JsonSerializable(typeof(SyncContactsRequest))]
[JsonSerializable(typeof(TrustIdentityRequest))]
[JsonSerializable(typeof(UnregisterDeviceRequest))]
[JsonSerializable(typeof(UpdateAccountSettingsRequest))]
[JsonSerializable(typeof(UpdateContactRequest))]
[JsonSerializable(typeof(UpdateGroupRequest))]
[JsonSerializable(typeof(UpdateProfileRequest))]
[JsonSerializable(typeof(VerifyNumberRequest))]

// Arrays/Collections
[JsonSerializable(typeof(List<Group>))]
[JsonSerializable(typeof(List<Attachment>))]
[JsonSerializable(typeof(List<ReadMessage>))]
[JsonSerializable(typeof(List<PreviewData>))]
[JsonSerializable(typeof(List<Mention>))]
[JsonSerializable(typeof(List<Device>))]
[JsonSerializable(typeof(List<Identity>))]
[JsonSerializable(typeof(List<Contact>))]
[JsonSerializable(typeof(List<Search>))]
[JsonSerializable(typeof(List<StickerPack>))]
[JsonSerializable(typeof(List<string>))]
public partial class JsonBotSerializerContext : JsonSerializerContext;